Controllers/SeguridadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Security.Policy;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity.Core.Objects;
using LEGASY.Models;
using System.Net;
using LEGASY.Encripta;

namespace LEGASY.Controllers
{
    
    public class SeguridadController : PrincipalController
    {
        // GET: Seguridad

        public ActionResult Modulos()
        {
            if (ValidaSesion(1))
             {

                List<Seguridad_Fn_MostrarModulos_Result> Modulos = new List<Seguridad_Fn_MostrarModulos_Result>();
                Modulos = db.Seguridad_Fn_MostrarModulos().ToList();
                return View(Modulos);

            }
            else
            {
                return Salir();
            }
           
           
        }
        [HttpGet]
        public ActionResult GuardarModulos( string respuesta)
        {
            if (ValidaSesion(1))
            {
                if (respuesta != null)
                {
                    ViewBag.Respuesta = respuesta;
                }

                return View();
            }
            else
            {
                return Salir();
            }
           
        }

        [HttpPost]
        public ActionResult GuardarModulos( string Nombre, string NombreCorto, string Descripcion, int Estado)
        {
            if (ValidaSesion())
            {
                JsonResult respuesta = new JsonResult();
                ObjectParameter Respuesta = new ObjectParameter("Respuesta", typeof(int));
                ObjectParameter Mensaje = new ObjectParameter("Mensaje", typeof(string));
                bool State = false;

                if (Estado == 1)
                {
                    State = true;
                }

                db.Seguridad_P_GuardarModulo(State, Nombre, NombreCorto, Descripcion, this.UsuarioActual.entryCode, DateTime.Now, Respuesta, Mensaje);

                int RespValue = Convert.ToInt32(Respuesta.Value);
                string MenValue = Convert.ToString(Mensaje.Value);

                if (RespValue == 1)
                {
                    respuesta.Data = new { estado = true, mensaje = "El Modulo se guardo correctamente!" };

                    return RedirectToAction("Modulos");
                }
                else
                {
                    ViewBag.Respuesta = MenValue;
                    return RedirectToAction("GuardarModulos", new { @respuesta = MenValue.ToString() });

                }
            }
            else
            {
                return Salir();
            }

         
        }
        [HttpGet]
        public ActionResult EditarModulo(int? Id, string respuesta)
        {
            if (ValidaSesion(1))
            {
                if (respuesta != null)
                {
                    ViewBag.Respuesta = respuesta;

                }

                var InfoModulo = db.Seguridad_Fn_ModuloSeleccionado(Id).FirstOrDefault();

                if (InfoModulo == null)
                {
                    ViewBag.Respuesta = "El Modulo ingresado no existe!";
                    return View();
                }
                else
                {

                    return View(InfoModulo);
                }
            }
            else
            {
                return Salir();
            }

    
        }
        [HttpPost]
        public ActionResult EditarModulo(int entryCode, int Estado, string Nombre, string NombreCorto, string Descripcion)
        {

            if (ValidaSesion())
            {
                ObjectParameter Respuesta = new ObjectParameter("Respuesta", typeof(int));
                ObjectParameter Mensaje = new ObjectParameter("Mensaje", typeof(string));
                bool State = false;

                if (Estado == 1)
                {
                    State = true;
                }

                db.Seguridad_P_EditarModulo(entryCode, State, Nombre, NombreCorto, Descripcion, this.UsuarioActual.entryCode, DateTime.Now, Respuesta, Mensaje);

                int RespValue = Convert.ToInt32(Respuesta.Value);
                string MenValue = Convert.ToString(Mensaje.Value);

                if (RespValue == 1)
                {


                    return RedirectToAction("EditarModulo", new { @Id = entryCode, @respuesta = MenValue.ToString() });
                }
                else
                {
                    ViewBag.Respuesta = MenValue;
                    return RedirectToAction("EditarModulo", new { @Id = entryCode, @respuesta = MenValue.ToString() });

                }
            }
            else
            {
                return Salir();
            }
           


        }


        public ActionResult ListaPermisos(int IdModulo)
        {
            if (ValidaSesion())
            {
                List<Seguridad_Fn_MostrarPermisos_Result> Permisos = new List<Seguridad_Fn_MostrarPermisos_Result>();
                Permisos = db.Seguridad_Fn_MostrarPermisos(IdModulo).ToList();
                ViewBag.IdModulo = IdModulo;

                return View(Permisos);
            }
            else
            {
                return Salir();
            }
         
        }


        [HttpGet]
        public ActionResult GuardarPermiso(int IdModulo, string respuesta)
        {
            if (ValidaSesion())
            {
                if (respuesta != null)
                {
                    ViewBag.Respuesta = respuesta;
                }
                ViewBag.IdModulo = IdModulo;

                var DatosModulo = db.Seguridad_Fn_MostrarModulos().Where(x => x.entryCode == IdModulo).FirstOrDefault();

                return View(DatosModulo);

            }
            else
            {
                return Salir();
            }

        }
        [HttpPost]
        public ActionResult GuardarPermiso(int IdModulo, int Estado, string NombrePermiso, string Descripcion)
        {
            if (ValidaSesion())
            {
                ObjectParameter Respuesta = new ObjectParameter("Respuesta", typeof(int));
                ObjectParameter Mensaje = new ObjectParameter("Mensaje", typeof(string));
                bool State = false;

                if (Estado == 1)
                {
                    State = true;
                }

                db.Seguridad_P_GuardarPermiso(IdModulo, State, NombrePermiso, Descripcion, this.UsuarioActual.entryCode, DateTime.Now, Respuesta, Mensaje);

                int RespValue = Convert.ToInt32(Respuesta.Value);
                string MenValue = Convert.ToString(Mensaje.Value);

                if (RespValue == 1)
                {


                    return RedirectToAction("ListaPermisos", new { @IdModulo = IdModulo });
                }
                else
                {
                    ViewBag.Respuesta = MenValue;
                    return RedirectToAction("GuardarPermiso", new { IdModulo = IdModulo, @respuesta = MenValue.ToString() });

                }
            }
            else
            {
                return Salir();
            }
          


        }
        [HttpGet]
        public ActionResult EditarPermiso(int? Id, string respuesta)
        {
            if (ValidaSesion())
            {
                if (respuesta != null)
                {
                    ViewBag.Respuesta = respuesta;

                }

                var InfoPermiso = db.Seguridad_Fn_PermisoSeleccionado(Id).FirstOrDefault();

                if (InfoPermiso == null)
                {
                    ViewBag.Respuesta = "El Permiso ingresado no existe!";
                    return View();
                }
                else
                {

                    return View(InfoPermiso);
                }

            }
            else
            {
                return Salir();
            }
         


        }
        [HttpPost]
        public ActionResult EditarPermiso(int entryCode, int Estado, string Nombre, string NombreCorto, string Descripcion)
        {
            if (ValidaSesion())
            {
                ObjectParameter Respuesta = new ObjectParameter("Respuesta", typeof(int));
                ObjectParameter Mensaje = new ObjectParameter("Mensaje", typeof(string));
                bool State = false;

                if (Estado == 1)
                {
                    State = true;
                }

                db.Seguridad_P_EditarModulo(entryCode, State, Nombre, NombreCorto, Descripcion, this.UsuarioActual.entryCode, DateTime.Now, Respuesta, Mensaje);

                int RespValue = Convert.ToInt32(Respuesta.Value);
                string MenValue = Convert.ToString(Mensaje.Value);

                if (RespValue == 1)
                {


                    return RedirectToAction("EditarModulo", new { @Id = entryCode, @respuesta = MenValue.ToString() });
                }
                else
                {
                    ViewBag.Respuesta = MenValue;
                    return RedirectToAction("EditarModulo", new { @Id = entryCode, @respuesta = MenValue.ToString() });

                }
            }
            else
            {
                return Salir();
            }

        }
        public ActionResult ListaUsuarios()
        {
            if (ValidaSesion(3))
            {
                
                List<Seguridad_Fn_MostrarUsuarios_Result> Usuarios = new List<Seguridad_Fn_MostrarUsuarios_Result>();
                Usuarios = db.Seguridad_Fn_MostrarUsuarios().ToList();

                return View(Usuarios);
                
            }
            else
            {
                return Salir();
            }

         
        }
        [HttpGet]
        public ActionResult RegistrarUsuario(string respuesta)
        {
            if (ValidaSesion())
            {
                if (respuesta != null)
                {

Views/Seguridad/EditarUsuario.cshtml
@using LEGASY.Models
@model Seguridad_Fn_UsuarioSeleccionado_Result
@{
    ViewBag.Title = "EditarUsuario";
}

<br />
<!-- Content Header (Page header) -->
<div class="card-header" style="background-color:white;">
    <div class="col-sm-6">
        <h1>Editar Usuarios en el sistema</h1>
    </div>

</div>

<br />

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">

                <div class="card-header">
                    <div class="col-sm-10">
                        <h3 class="card-title">Datos del Usuario</h3>
                    </div>
                    <br />
                    <hr />
                    <div class="card-body pad table-responsive">

                        @*Todo el Contenido Aqui*@
                        <!-- Horizontal Form -->
                        <div class="card card-default">
                            <div class="card-header">
                                <h3 class="card-title">Formulario</h3>
                            </div>

                            @if (ViewBag.Respuesta != null)
                            {
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="alert alert-warning">
                                            @ViewBag.Respuesta

                                        </div>
                                    </div>
                                </div>
                            }

                            <!-- /.card-header -->
                            <!-- form start -->
                            @using (Html.BeginForm())
                            {
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group row">
                                                <label for="Name" class="col-sm-2 col-form-label">Nombre</label>
                                                <div class="col-sm-10">
                                                    <input type="text" class="form-control" id="NombreDesplegable" name="NombreDesplegable" placeholder="Nombre Desplegable">
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label for="NombreCorto" class="col-sm-2 col-form-label">Nombre Usuario</label>
                                                <div class="col-sm-10">
                                                    <input type="text" class="form-control" id="NombreUsuario" name="NombreUsuario" placeholder="Nombre Usuario">
                                                </div>
                                            </div>

                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group row">
                                                <label for="Descrípcion" class="col-sm-2 col-form-label">Correo</label>
                                                <div class="col-sm-10">
                                                    <input type="email" class="form-control" id="Correo" name="Correo" placeholder="Correo">
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label for="Descrípcion" class="col-sm-2 col-form-label">Contraseña Inicial</label>
                                                <div class="col-sm-10">
                                                    <input type="text" class="form-control" id="Contraseña" name="Contraseña" placeholder="Contraseña Inicial">
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                                <!-- /.card-body -->
                                <div class="card-footer">
                                    <div class="col-md-12">
                                        
                                            <button type="submit" class="btn btn-info"><i class="fa fa-save"></i> Guardar</button>
                                            <a class="btn btn-primary" href="@Url.Action("ModulosUsuario", "Seguridad", new {IdUsuario = Model.entryCode})">

                                                <i class="fa fa-circle-notch"></i> Modulos
                                            </a>  <a class="btn btn-primary" href="@Url.Action("PermisosUsuario", "Seguridad", new {IdUsuario = Model.entryCode})">

                                                <i class="fa fa-arrow-alt-circle-right"></i> Permisos
                                            </a>
                                            <button type="submit" class="btn btn-danger float-right"><i class="fa fa-eraser"></i> Cancelar</button>
                                        
                                       
                                    </div>
                                   
                                    
                                </div>

                                <!-- /.card-footer -->
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Seguridad/ListaPermisos.cshtml
@using LEGASY.Models
@model  List<LEGASY.Models.Seguridad_Fn_MostrarPermisos_Result>
@{
    ViewBag.Title = "ListaPermisos";
    LegasyEntities db = new LegasyEntities();
    int ModuloActualId = ViewBag.IdModulo;
    var DatosModulo = db.Seguridad_Fn_MostrarModulos().Where(x => x.entryCode == ModuloActualId).FirstOrDefault();
}

<br />
<!-- Content Header (Page header) -->
<div class="card-header" style="background-color:white;">
    <div class="col-sm-6">
        <h1>Lista de Permisos</h1>
    </div>


</div>

<br />
<!-- Main content -->
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="row mb-2">
                        <div class="col-sm-11">
                            <h3 class="card-title">Permisos Registrados en <strong>@DatosModulo.entryName</strong> </h3>
                        </div>

                        <div class="col-sm-1">
                            @*<a href=@Url.Action("GuardarModulos","Modulos") class="btn btn-outline-primary btn-block">
                                    <i class="fa fa-save"></i>
                                    <p>Registrar Nuevo</p>
                                </a>*@
                            @Html.ActionLink("Registrar nuevo", "GuardarPermiso", new { IdModulo = ModuloActualId }, new { @class = "btn btn-outline-primary btn-block btn-xs" })
                            @*<button type="button" class="btn btn-outline-primary btn-block"><i class="fa fa-save"></i> Registrar Nuevo</button>*@
                        </div>
                    </div>
                </div>

                <div class="card-body pad table-responsive">
                    <table id="ListaModulos" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Modulo</th>
                                <th>Permiso</th>
                                <th>Descripcion</th>
                                <th>Estatus</th>
                                <th></th>
                    
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                              
                                <tr>
                                    <td>@item.entryCode</td>
                                    <td>@item.entryNameModulo</td>
                                    <td>@item.entryNamePermiso</td>
                                    <td>@item.entryDescription</td>
                                    <td>@item.Estado</td>                          
                                    <td>
                                        <a class="btn btn-app bg-success">
                                            <i class="fas fa-edit"></i> Editar
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>

                    </table>
                </div>
                <!-- /.card-body -->
            </div>

        </div>
    </div>
</div>


@section scripts{

    <script>
        $(function () {

            $("#ListaModulos").DataTable({
                "responsive": true, "lengthChange": true, "autoWidth": true,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }

            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)')



        });

    </script>

}

Views/Seguridad/ListaUsuarios.cshtml
@using LEGASY.Models
@model  List<LEGASY.Models.Seguridad_Fn_MostrarUsuarios_Result>
@{
    ViewBag.Title = "ListaUsuarios";
   
}

<br />
<!-- Content Header (Page header) -->
<div class="card-header" style="background-color:white;">
    <div class="col-sm-6">
        <h1>Lista de Usuarios</h1>
    </div>


</div>

<br />
<!-- Main content -->
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="row mb-2">
                        <div class="col-sm-11">
                            <h3 class="card-title">Usuarios registrados en el sistema </h3>
                        </div>

                        <div class="col-sm-1">
                            @*<a href=@Url.Action("GuardarModulos","Modulos") class="btn btn-outline-primary btn-block">
                                    <i class="fa fa-save"></i>
                                    <p>Registrar Nuevo</p>
                                </a>*@
                            @Html.ActionLink("Registrar nuevo", "RegistrarUsuario", null,  new { @class = "btn btn-outline-primary btn-block btn-xs" })
                            @*<button type="button" class="btn btn-outline-primary btn-block"><i class="fa fa-save"></i> Registrar Nuevo</button>*@
                        </div>
                    </div>
                </div>

                <div class="card-body pad table-responsive">
                    <table id="ListaUsuarios" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Nombre</th>
                                <th>Nombre a Mostrar</th>
                                <th>Correo</th>
                                <th>Estado</th>
                                <th></th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {

                                <tr>
                                    <td>@item.entryCode</td>
                                    <td>@item.entryUserName</td>
                                    <td>@item.entryDisplayName</td>
                                    <td>@item.entryEmail</td>
                                    <td>@item.entryCodeStatus</td>
                                    <td>
                                        <a class="btn btn-app bg-success" href="@Url.Action("EditarUsuario", "Seguridad", new {Id = item.entryCode})">
                                            <i class="fas fa-edit"></i> Editar
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>

                    </table>
                </div>
                <!-- /.card-body -->
            </div>

        </div>
    </div>
</div>


@section scripts{

    <script>
        $(function () {

            $("#ListaUsuarios").DataTable({
                "responsive": true, "lengthChange": true, "autoWidth": true,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }

            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)')



        });

    </script>

}

Views/Seguridad/Modulos.cshtml
@using LEGASY.Models
@model  List<LEGASY.Models.Seguridad_Fn_MostrarModulos_Result>
@{
    ViewBag.Title = "Modulos";
}

<br />
<!-- Content Header (Page header) -->
<div class="card-header" style="background-color:white;">
    <div class="col-sm-6">
        <h1>Lista de Modulos</h1>
    </div>


</div>

<br />
<!-- Main content -->
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="row mb-2">
                        <div class="col-sm-11">
                            <h3 class="card-title">Modulos Configurados</h3>
                        </div>

                        <div class="col-sm-1">
                            @*<a href=@Url.Action("GuardarModulos","Modulos") class="btn btn-outline-primary btn-block">
                                <i class="fa fa-save"></i>
                                <p>Registrar Nuevo</p>
                            </a>*@
                            @Html.ActionLink("Registrar nuevo", "GuardarModulos", null, new { @class = "btn btn-outline-primary btn-block btn-xs" })
                            @*<button type="button" class="btn btn-outline-primary btn-block"><i class="fa fa-save"></i> Registrar Nuevo</button>*@
                        </div>
                    </div>
                 </div>

                    <div class="card-body pad table-responsive">
                        <table id="ListaModulos" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Nombre</th>
                                    <th>Nombre Corto</th>
                                    <th>Descripcion</th>
                                    <th>Estatus</th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    string estado = "";
                                    <tr>
                                        <td>@item.entryCode</td>
                                        <td>@item.entryName</td>
                                        <td>@item.entryShortName</td>
                                        <td>@item.entryDescription</td>

                                        <td>
                                            @if (item.entryCodeStatus == true)
                                            {
                                                estado = "Activo";
                                            }
                                            else
                                            {
                                                estado = "Inactivo";
                                            }
                                            @estado
                                        </td>
                                        <td>
                                            <a class="btn btn-app bg-info" href="@Url.Action("EditarModulo", "Seguridad", new {Id = item.entryCode})">

                                                <i class="fas fa-edit"></i> Editar
                                            </a>
                                        </td>
                                        <td>
                                            <a class="btn btn-app bg-primary" href="@Url.Action("ListaPermisos", "Seguridad", new {IdModulo = item.entryCode})">

                                                <i class="fas fa-share"></i> Permisos
                                            </a>
                                        </td>
                                        <td>
                                            <a class="btn btn-app bg-success" href="@Url.Action("ListaUsuarios", "Seguridad")">

                                                <i class="fas fa-users"></i> Usuarios
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>

                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>

        </div>
    </div>
</div>


@section scripts{

    <script>
        $(function () {

            $("#ListaModulos").DataTable({
                "responsive": true, "lengthChange": true, "autoWidth": true,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }

            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)')


          
        });

    </script>

}