Controllers/PersonalizaController.cs
using LEGASY.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LEGASY.Encripta;

namespace LEGASY.Controllers
{
 
    public class PersonalizaController : PrincipalController
    {

        #region #################### Empresas ###################
        // GET: Personaliza
        public ActionResult Index()
        {
            if (ValidaSesion(7))
            {
                List<Personaliza_Fn_ListaEmpresas_Result> listaEmpresas = new List<Personaliza_Fn_ListaEmpresas_Result>();

                listaEmpresas = db.Personaliza_Fn_ListaEmpresas().ToList();

                return View(listaEmpresas);
            }
            else
            {
                return Salir();
            }
            
        }

        [HttpGet]
        public ActionResult GuardarEmpresa(string respuesta)
        {

            if (ValidaSesion(7))
            {
                if (respuesta != null)
                {
                    ViewBag.Respuesta = respuesta;
                }

                return View();
            }
            else
            {
                return Salir();
            }

           
        }
        [HttpPost]
        public ActionResult GuardarEmpresa(string Nombre, string Descripcion, string Persona, string Direccion, string Identidad1, string Identidad2, string Identidad3, string Telefono1, string Telefono2, string Telefono3, string Correo, string Comentarios)
        {
            try
            {
              
               

                ObjectParameter Respuesta = new ObjectParameter("Respuesta", typeof(int));
                ObjectParameter Mensaje = new ObjectParameter("Mensaje", typeof(string));

                db.Personaliza_P_GuardarEmpresas(Nombre, Descripcion, Persona, Direccion, Identidad1, Identidad2, Identidad3, Telefono1, Telefono2, Telefono3, Correo, Comentarios, this.UsuarioActual.entryCode, DateTime.Now,  Respuesta, Mensaje);

                int RespValue = Convert.ToInt32(Respuesta.Value);
                string MenValue = Convert.ToString(Mensaje.Value);

                if (RespValue == 1)
                {

                    return RedirectToAction("Index");
                }
                else
                {
                  
                    return RedirectToAction("GuardarEmpresa", new { @respuesta = MenValue.ToString() });

                }
            }
          
            catch (Exception ex)
            {
                string Error;

                if(ex.InnerException != null)
                {
                    Error = ex.InnerException.Message;
                }
                else
                {
                    Error = ex.Message;
                }

                return RedirectToAction("GuardarEmpresa", new { @respuesta = Error });
            }
        }

        [HttpGet]
        public ActionResult EditarEmpresa(int IdEmpresa)
        {
            if (ValidaSesion(7))
            {
                Personaliza_Fn_EmpresaSeleccionada_Result DatosEmpresa = new Personaliza_Fn_EmpresaSeleccionada_Result();

                DatosEmpresa = db.Personaliza_Fn_EmpresaSeleccionada(IdEmpresa).FirstOrDefault();

                return View(DatosEmpresa);
            }
            else
            {
                return Salir();
            }
          
        }

        [HttpPost]
        public ActionResult EditarEmpresa(Int64 IdEmpresa, string Nombre, string Descripcion, string Persona, string Direccion, string Identidad1, string Identidad2, string Identidad3, string Telefono1, string Telefono2, string Telefono3, string Correo, string Comentarios)
        {

            if (ValidaSesion())
            {
                try
                {
                

                    ObjectParameter Respuesta = new ObjectParameter("Respuesta", typeof(int));
                    ObjectParameter Mensaje = new ObjectParameter("Mensaje", typeof(string));

                    db.Personaliza_P_EditarEmpresas(IdEmpresa, Nombre, Descripcion, Persona, Direccion, Identidad1, Identidad2, Identidad3, Telefono1, Telefono2, Telefono3, Correo, Comentarios, this.UsuarioActual.entryCode, DateTime.Now, Respuesta, Mensaje);

                    int RespValue = Convert.ToInt32(Respuesta.Value);
                    string MenValue = Convert.ToString(Mensaje.Value);

                    if (RespValue == 1)
                    {

                        return RedirectToAction("Index");
                    }
                    else
                    {

                        return RedirectToAction("EditarEmpresa", new { @respuesta = MenValue.ToString() });

                    }
                }

                catch (Exception ex)
                {
                    string Error;

                    if (ex.InnerException != null)
                    {
                        Error = ex.InnerException.Message;
                    }
                    else
                    {
                        Error = ex.Message;
                    }

                    return RedirectToAction("EditarEmpresa", new { @respuesta = Error });
                }
            }
            else
            {
                return Salir();
            }
          
        }
        #endregion

        #region ################ Sucursales #################
        public ActionResult GuardarSucursal(int IdEmpresa)
        {
            if (ValidaSesion(8))
            {
                Personaliza_Fn_EmpresaSeleccionada_Result Empresa = new Personaliza_Fn_EmpresaSeleccionada_Result();

                Empresa = db.Personaliza_Fn_EmpresaSeleccionada(IdEmpresa).FirstOrDefault();

                return View(Empresa);
            }
            else
            {
                return Salir();
            }
        
        }

        [HttpPost]
        public ActionResult GuardarSucursal(int IdEmpresa, string Nombre, string Descripcion, string Persona, string Direccion, string Identidad1, string Identidad2, string Identidad3, string Telefono1, string Telefono2, string Telefono3, string Correo, string Comentarios)
        {
            if (ValidaSesion())
            {
                try
                {

                    ObjectParameter Respuesta = new ObjectParameter("Respuesta", typeof(int));
                    ObjectParameter Mensaje = new ObjectParameter("Mensaje", typeof(string));

                    db.Personaliza_P_GuardarSucursal(IdEmpresa, Nombre, Descripcion, Persona, Direccion, Identidad1, Identidad2, Identidad3, Telefono1, Telefono2, Telefono3, Correo, Comentarios, this.UsuarioActual.entryCode, DateTime.Now, Respuesta, Mensaje); ;

                    int RespValue = Convert.ToInt32(Respuesta.Value);
                    string MenValue = Convert.ToString(Mensaje.Value);

                    if (RespValue == 1)
                    {
                        //Listado de Sucursales
                        return RedirectToAction("ListaSucursales");
                    }
                    else
                    {

                        return RedirectToAction("GuardarEmpresa", new { @respuesta = MenValue.ToString() });

                    }
                }

                catch (Exception ex)
                {
                    string Error;

                    if (ex.InnerException != null)
                    {
                        Error = ex.InnerException.Message;
                    }
                    else
                    {
                        Error = ex.Message;
                    }

                    return RedirectToAction("GuardarEmpresa", new { @respuesta = Error });
                }

            }
            else
            {
                return Salir();
            }

        }
        public ActionResult ListaSucursales(string respuesta)
        {
            if (ValidaSesion(8))
            {
                List<Personaliza_Fn_ListaSucursales_Result> Sucursales = new List<Personaliza_Fn_ListaSucursales_Result>();

                Sucursales = db.Personaliza_Fn_ListaSucursales().ToList();

                return View(Sucursales);

            }
            else
            {
                return Salir();
            }

        }

        #endregion

        #region ############### Cuentas de Banco ###################
        public ActionResult ListaCuentasBanco(string respuesta)
        {
            if (ValidaSesion(9))
            {
                List<Personaliza_Fn_CuentasdeBanco_Result> CuentasBanco = new List<Personaliza_Fn_CuentasdeBanco_Result>();

                CuentasBanco = db.Personaliza_Fn_CuentasdeBanco().ToList();

                return View(CuentasBanco);

            }
            else
            {
                return Salir();
            }

        }

        [HttpGet]
        public ActionResult CrearCuentaBanco(string respuesta)
        {

            if (ValidaSesion(9))
            {
                if (respuesta != null)
                {
                    ViewBag.Respuesta = respuesta;
                }

                List<SelectListItem> TipoCuenta = new List<SelectListItem>();
                TipoCuenta.Add(new SelectListItem { Value = "", Text = "[-- Seleccionar Tipo Cuenta --]" });
                foreach (var item in db.Personaliza_Fn_TipoCuenta().ToList())
                {
                    TipoCuenta.Add(new SelectListItem { Value = item.entryCode.ToString(), Text = item.entryName.ToString() });
                }

                ViewBag.TipoCuentaBancos = TipoCuenta;

                List<SelectListItem> Moneda = new List<SelectListItem>();
                Moneda.Add(new SelectListItem { Value = "", Text = "[-- Seleccionar Moneda --]" });
                foreach (var item in db.Personaliza_Fn_Monedas().ToList())
                {

Views/Personaliza/Index.cshtml
@using LEGASY.Models
@model List<LEGASY.Models.Personaliza_Fn_ListaEmpresas_Result>
@{
        ViewBag.Title = "Index";
}

    <br />
    <!-- Content Header (Page header) -->
    <div class="card-header" style="background-color:white;">
        <div class="col-sm-6">
            <h1>Empresas</h1>
        </div>
    </div>

    <br />

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                   
                    <div class="card-header">
                        <div class="row mb-2">
                            <div class="col-sm-11">
                                <h3 class="card-title">Listado de Empresas</h3>
                            </div>
                            <div class="col-sm-1">

                                @Html.ActionLink("Registrar nuevo", "GuardarEmpresa", null, new { @class = "btn btn-outline-primary btn-block btn-xs" })

                            </div>
                        </div>
                    </div>
                    <div class="card-body pad table-responsive">

                        <table id="ListaEmpresas" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Nombre</th>
                                    <th>Descripcion</th>
                                    <th>Direccion</th>
                                    <th>Id1</th>
                                    <th>Telefono1</th>
                                    <th>Correo</th>
                                    <th></th>
                                    <th></th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {

                                    <tr>
                                        <td>@item.entryCode</td>
                                        <td>@item.entryName</td>
                                        <td>@item.entryDescription</td>
                                        <td>@item.entryAddress</td>
                                        <td>@item.entryID1</td>
                                        <td>@item.entryPhone1</td>
                                        <td>@item.entryEmail</td>

                                        <td>
                                            <a class="btn btn-success btn-block" href="@Url.Action("EditarEmpresa", "Personaliza", new {IdEmpresa = item.entryCode})">
                                                <i class="fas fa-edit"></i> Editar
                                            </a>
                                        </td>
                                        <td>
                                            <a class="btn btn-info btn-block" href="@Url.Action("GuardarSucursal", "Personaliza", new {IdEmpresa = item.entryCode})">
                                                <i class="fas fa-save"></i> Sucursal
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>

                        </table>

                        @*Todo el Contenido Aqui*@

                    </div>


                </div>
            </div>
        </div>
    </div>

    @section scripts{

        <script>
        $(function () {

            $("#ListaEmpresas").DataTable({
                "responsive": true, "lengthChange": true, "autoWidth": true,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }

            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)')



        });

        </script>

    }

Views/Personaliza/ListaPeriodosPresupuesto.cshtml
@using LEGASY.Models
@model List<LEGASY.Models.Personaliza_Fn_ListaPeriodosPresupuesto_Result>
@{
    ViewBag.Title = "ListaPeriodosPresupuesto";
}

<br />
<!-- Content Header (Page header) -->
<div class="card-header" style="background-color:white;">
    <div class="col-sm-6">
        <h1>Periodos de Presupuesto</h1>
    </div>
</div>

<br />

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">

                <div class="card-header">
                    <div class="row mb-2">
                        <div class="col-sm-11">
                            <h3 class="card-title">Listado de Periodos de Presupuesto</h3>
                        </div>
                        <div class="col-sm-1">

                            @Html.ActionLink("Registrar nuevo", "CrearPeriodosPresupuesto", null, new { @class = "btn btn-outline-primary btn-block btn-xs" })

                        </div>
                    </div>
                </div>
                <div class="card-body pad table-responsive">

                    <table id="ListaPeriodos" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Estado</th>
                                <th>Nombre</th>
                                <th>Descripcion</th>
                                <th>FechaCreacion</th>
                                <th></th>


                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                string Estado;
                                <tr>
                                    <td>@item.entryCode</td>
                                    <td>
                                        @if (item.entryCodeStatus == true)
                                        {
                                         Estado = "Activo";
                                        }else
                                        {
                                         Estado = "Inactivo";
                                        }                                           
                                        @Estado
                                    </td>
                                    <td>@item.entryName</td>
                                    <td>@item.entryDescription</td>
                                    <td>@item.dateCreate</td>
                                    <td>
                                        <a class="btn btn-success btn-block" href="@Url.Action("EditarPeriodoPresupuesto", "Personaliza", new {Id = item.entryCode})">
                                            <i class="fas fa-edit"></i> Editar
                                        </a>
                                    </td>

                                </tr>
                            }
                        </tbody>

                    </table>

                    @*Todo el Contenido Aqui*@

                </div>


            </div>
        </div>
    </div>
</div>

@section scripts{

    <script>
        $(function () {

            $("#ListaPeriodos").DataTable({
                "responsive": true, "lengthChange": true, "autoWidth": true,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }

            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)')



        });

    </script>

}

Views/Personaliza/ListaTiposGasto.cshtml
@using LEGASY.Models
@model List<LEGASY.Models.Personaliza_Fn_ListaTipoGasto_Result>
@{
    ViewBag.Title = "ListaTipoGasto";
}

<br />
<!-- Content Header (Page header) -->
<div class="card-header" style="background-color:white;">
    <div class="col-sm-6">
        <h1>Tipos de Gasto</h1>
    </div>
</div>

<br />

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">

                <div class="card-header">
                    <div class="row mb-2">
                        <div class="col-sm-11">
                            <h3 class="card-title">Listado de Tipos de Gasto</h3>
                        </div>
                        <div class="col-sm-1">

                            @Html.ActionLink("Registrar nuevo", "CrearTipoGasto", null, new { @class = "btn btn-outline-primary btn-block btn-xs" })

                        </div>
                    </div>
                </div>
                <div class="card-body pad table-responsive">

                    <table id="ListaTipoGasto" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Estado</th>
                                <th>Nombre</th>
                                <th>Descripcion</th>
                                <th>FechaCreacion</th>
                                <th></th>


                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                string Estado;
                                <tr>
                                    <td>@item.entryCode</td>
                                    <td>
                                        @if (item.entryCodeStatus == true)
                                        {
                                            Estado = "Activo";
                                        }
                                        else
                                        {
                                            Estado = "Inactivo";
                                        }
                                        @Estado
                                    </td>
                                    <td>@item.entryName</td>
                                    <td>@item.entryDescription</td>
                                    <td>@item.dateCreate</td>
                                    <td>
                                        <a class="btn btn-success btn-block" href="@Url.Action("EditarTipoGasto", "Personaliza", new {Id = item.entryCode})">
                                            <i class="fas fa-edit"></i> Editar
                                        </a>
                                    </td>

                                </tr>
                            }
                        </tbody>

                    </table>

                    @*Todo el Contenido Aqui*@

                </div>


            </div>
        </div>
    </div>
</div>

@section scripts{

    <script>
        $(function () {

            $("#ListaTipoGasto").DataTable({
                "responsive": true, "lengthChange": true, "autoWidth": true,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }

            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)')



        });

    </script>

}

Views/Personaliza/ListaTiposPretension.cshtml
@using LEGASY.Models
@model List<LEGASY.Models.Personaliza_Fn_ListaTipoPretension_Result>
@{
    ViewBag.Title = "ListaTipoPretension";
}

<br />
<!-- Content Header (Page header) -->
<div class="card-header" style="background-color:white;">
    <div class="col-sm-6">
        <h1>Tipos de Pretension</h1>
    </div>
</div>

<br />

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">

                <div class="card-header">
                    <div class="row mb-2">
                        <div class="col-sm-11">
                            <h3 class="card-title">Listado de Tipos de Pretension</h3>
                        </div>
                        <div class="col-sm-1">

                            @Html.ActionLink("Registrar nuevo", "CrearTipoPretension", null, new { @class = "btn btn-outline-primary btn-block btn-xs" })

                        </div>
                    </div>
                </div>
                <div class="card-body pad table-responsive">

                    <table id="ListaTipoPrentension" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Estado</th>
                                <th>Nombre</th>
                                <th>Descripcion</th>
                                <th>FechaCreacion</th>
                                <th></th>


                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                string Estado;
                                <tr>
                                    <td>@item.entryCode</td>
                                    <td>
                                        @if (item.entryCodeStatus == true)
                                        {
                                            Estado = "Activo";
                                        }
                                        else
                                        {
                                            Estado = "Inactivo";
                                        }
                                        @Estado
                                    </td>
                                    <td>@item.entryName</td>
                                    <td>@item.entryDescription</td>
                                    <td>@item.dateCreate</td>
                                    <td>
                                        <a class="btn btn-success btn-block" href="@Url.Action("EditarTipoPretension", "Personaliza", new {Id = item.entryCode})">
                                            <i class="fas fa-edit"></i> Editar
                                        </a>
                                    </td>

                                </tr>
                            }
                        </tbody>

                    </table>

                    @*Todo el Contenido Aqui*@

                </div>


            </div>
        </div>
    </div>
</div>

@section scripts{

    <script>
        $(function () {

            $("#ListaTipoPrentension").DataTable({
                "responsive": true, "lengthChange": true, "autoWidth": true,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }

            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)')



        });

    </script>

}